<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ComputeSkinningSample</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <StrideRoot>$(MSBuildThisFileDirectory)../../../../</StrideRoot>
    <StrideContainsAssetTypes>true</StrideContainsAssetTypes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stride.Engine" Version="4.5.0-dev" />
    <PackageReference Include="Stride.UI" Version="4.5.0-dev" />
    <PackageReference Include="Stride.Particles" Version="4.5.0-dev" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
